# docker-compose.yml

version : '3'

services:
  nginx:
    restart: always
    image: nginx:latest
    volumes:
      - static_volume:/usr/src/app/_static
      - media_volume:/urs/src/app/_media
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
  web:
    build: .
    image: web:latest
    restart: always
    env_file: .env
    command: daphne config.asgi:application --port 8000 --bind 0.0.0.0 -v2
    volumes:
      - static_volume:/usr/src/app/_static
      - ./:/usr/src/app/
    expose:
      - 8000
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
volumes:
  static_volume:
  media_volume: