# Generated by Django 4.2.7 on 2023-11-28 08:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='like_goods', to=settings.AUTH_USER_MODEL),
        ),
    ]
