# Generated by Django 5.0 on 2024-01-04 10:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0005_alter_comment_options_alter_recomment_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="design",
            options={},
        ),
    ]
